//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeMVC.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public int IDExp { get; set; }
        public string Company { get; set; }
        public string Title { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> FromYear { get; set; }
        public Nullable<System.DateTime> ToYear { get; set; }
        public string Description { get; set; }
        public Nullable<int> IDPers { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
